"""
# Generated by hand: renamed from 0002_country_and_more.py
"""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(db_index=True, max_length=5, unique=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name="blogview",
            new_name="analytics_b_timesta_4d5d03_idx",
            old_name="analytics_b_timesta_94c490_idx",
        ),
        migrations.AlterField(
            model_name="blogview",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="views",
                to="analytics.country",
            ),
        ),
    ]
