"""
# Generated by hand: renamed from 0004_add_blog_ids.py
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_create_daily_analytics_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyanalyticssummary",
            name="blog_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of distinct blog IDs for this day/country/author",
                null=True,
            ),
        ),
    ]
